### ISSUE TITLE
Return data from modal

### ISSUE THREAD

**Issue by rodrix** [nonplus/angular-ui-router-uib-modal#11]
In this approach, has a way to return data from modal controller to parent state controller? Callback? Emit\Broadcast Event? Use service to hold data between state transitions?

Thanks.

**Comment by nonplus** [comment]
No, if you need data returned from a modal, you shouldn't be using a modal state but simply use the `uib-modal` as documented.

**Comment by octavioamu** [comment]
I now is a little late but maybe can help someone. One way to archive this is 
in your modal controller :
```
$uibModalInstance.dismiss(changeEvent());
function changeEvent () {
    $scope.$on("modal.closing",function(){
       $rootScope.$broadcast("modalClosing",DATA);
    });
  }
```
Then in the parent you get it like this:
```
$scope.$on("modalClosing",function(event,data){
    console.log('this is the data from the child', data)
})
```
I think there are some cases when is needed to have route and modal, for example when the modal is used to edit a single item in a list and the modal is used to display the single element, when you close the modal you need that changes be reflected in the list without refresh and get the whole list again.
