### ISSUE TITLE
How to get modal result promise in caller

### ISSUE THREAD

**Issue by redhead** [nonplus/angular-ui-router-uib-modal#2]
When I call `$state.go('modalState')` it returns (as normal) a promise of the transition. How can I get the promise of the modal result, so I can run some code after the modal closes/dismisses?

**Comment by redhead** [comment]
I figured out how to get the modal result promise instead, but it involves decorating the `$state.transitionTo()` method and passing some a param to the modal state that contains the deffered object that is resolved/rejected in your `onEnter` callback depending on the modal result.

Would you be interested in that feature to be included in this library? I haven't found any other way how to do this more cleanly though.

**Comment by nonplus** [comment]
If the caller relies on the result of the modal, it's usually an indication that the modal shouldn't be configured as a ui-router state. Instead the controller should simply call `$uibModal.open()`.  Conversely, a modal state controller shouldn't need to inject the `$uibModalInstance`; it should close the modal by navigating to another (non-child) state, e.g. `$state.go("^")`.

In my applications I use `$uibModal.open()` for simple modals or modals whose return value I care about (e.g. confirmations and alerts) and use modal states for stuff that could also make sense in a non-modal context. 

The pattern I often use is:

```
$stateProvider
  .state('list', {
    resolve: {
      items: ...
    },
    controller: function($scope, items) { ... }
  }),
  .state('list.create', {
    modal: true,
    controller: function($scope, $state) {
      $scope.submit = function() {
        var item = ...;
        $state.go("^", null, { reload: true });
      };
    }
  })
  .state('list.edit', {
    modal: ['item'],
    params: {
      id: { type: 'int' }
    },
    resolve: {
      item: function(items) { return items[item] }
    },
    controller: function($scope, $state, item) {
      $scope.submit = function() {
        ... update item & save to server
        $state.go("^", null, { reload: true });
      };
    }
  })
;
```

Having said that, you _might_ be able to achieve this by making the deferred a state parameter of the modal state.  I.e. something along the lines of:

```
// Configuration

$stateProvider.state('myModal', {
  modal: true,
  params: {
    dfd: { type: 'any' }
  },
  controller: function($uibModalInstance, dfd) {
    if (dfd) {
      $uibModalInstance.result.then(function(result) {
        dfd.resolve(result);
      }, function(err) {
        dfd.reject(err);
      });
    }
);

// Usage:

var dfd = $q.defer();
$state.go('myModal', { dfd: dfd });
dfd.then(...);
```

But, to reiterate, I would avoid using the $uibModalProvider in modal state controllers and I would not treat a state a something that returns a value.

**Comment by redhead** [comment]
I think you've got a point. I thought that having two ways (modal state and $uibModal.open) was a bit confusing to be spread in the project, and tried to replace all the modals to the modal state way. But semantically it doesn't make much sense.

Thanks. I think you can close this, if you want
