### ISSUE TITLE
Dynamic parent state 

### ISSUE THREAD

**Issue by nmarcetic** [nonplus/angular-ui-router-uib-modal#21]
Hi @nonplus, 
First of all, great job :) Thank you for this nice module. I wanted to pick your brain about something. 
I need a dynamic parent state, so I can open a modal from any ware, for example from header, click on header button (I dunno whats the current state, what's the parent) and I want to keep user on same state and on close/dismiss redirect them back. Sounds complicated but its not :) I want same behavior as simple bootstrap modal open from any ware , keep current state in background.

If you have any suggestion , what would be awesome :) Thanks!

**Comment by nickgrealy** [comment]
I've got the same issue (a terms and conditions page that can be opened from anywhere).

I suspect the solution is [just use the vanilla `uib` modal](https://angular-ui.github.io/bootstrap/#!#modal) (without setting up a route).

**Comment by nonplus** [comment]
@nmarcetic, I use the same approach as @nickgrealy.  For simple reusable modals, I just open them as a vanilla uib-modal and don't create separate states for them.

The one thing you want to be careful about is to ensure that the modal is closed when the user navigates to a different state (usually using the browser back button).  To do so, in the modal's controller, listen to the `"$stateChangeStart"` event and dismiss them modal, e.g.

```javascript
$scope.$on("$stateChangeStart", function () { $scope.$dismiss("close"); });
```

Occasionally I have more complex modals that manage state.  Usually it's a modal that uses tabs with separate sub-states, or - more rarely - that opens a nested modal.  If I need to reuse this type of modal,  I implement the state configuration in a function that takes the parent state name as a parameter, and uses it to build the state names it registers:

```javascript
// Shared modal states configuration
function configSomeModalStates(
    stateProvider,
    parentState
) {
    const modalState = parentState + ".some-modal";

    stateProvider
        .state(modalState, {
            url: "/some-modal?param1&param2&param3",
            params: { ... },
            modal: [...],
            controller: SomeModalController,
            templateUrl: ...,
            resolve: { ... }
        }
        .state(modalState + ".sub-state", {
            ...
        }
    ;
}


// Usages
configSomeModalStates($stateProvider, "home");
...
configSomeModalStates($stateProvider, "about");
...
configSomeModalStates($stateProvider, "plan.details");
```

**Comment by xDisfigure** [comment]
Today, You should take a loot about ui-router-extra, Sticky State should be the appropriate thing you're looking for https://github.com/ui-router/sticky-states
